# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=80)),
                ('record_id', models.CharField(max_length=80)),
                ('sub_domain', models.CharField(max_length=160)),
                ('record_type', models.CharField(max_length=80)),
                ('record_line_id', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=160)),
            ],
            options={
                'db_tablespace': 'domain',
            },
        ),
    ]
