# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linename', models.CharField(max_length=80)),
            ],
            options={
                'db_tablespace': 'line',
            },
        ),
    ]
