# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_line_id',
            new_name='record_line',
        ),
    ]
