# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=160)),
                ('domain', models.CharField(max_length=160)),
                ('operation', models.CharField(max_length=160)),
                ('record_type', models.CharField(max_length=160)),
                ('record_name', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=160)),
                ('line', models.CharField(max_length=160)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_tablespace': 'logs',
            },
        ),
    ]
